### ISSUE TITLE
Generate Image API not working with Foocus 2.5.5 after update

### ISSUE THREAD

**Issue by TriptSharma** [toutjavascript/FoooXus-Fooocus-Extender#15]
I am passing the encoded empty value (from https://github.com/toutjavascript/FoooXus-Fooocus-Extender/blob/main/src/api.py#L39) as an api call from my local system to the colab hosted gradio app. However, it's giving me the following error:

```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\work\gen-pipe\gen-env\Lib\site-packages\gradio_client\client.py", line 468, in predict
    ).result()
      ^^^^^^^^
  File "c:\work\gen-pipe\gen-env\Lib\site-packages\gradio_client\client.py", line 1499, in result
    return super().result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\gen-pipe\gen-env\Lib\site-packages\gradio_client\compatibility.py", line 63, in _inner
    data = self.serialize(*data)
           ^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\gen-pipe\gen-env\Lib\site-packages\gradio_client\compatibility.py", line 244, in serialize
    o = tuple([s.serialize(d) for s, d in zip(self.serializers, data)])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\gen-pipe\gen-env\Lib\site-packages\gradio_client\compatibility.py", line 244, in <listcomp>
    o = tuple([s.serialize(d) for s, d in zip(self.serializers, data)])
               ^^^^^^^^^^^^^^
  File "c:\work\gen-pipe\gen-env\Lib\site-packages\gradio_client\serializing.py", line 188, in serialize
    return utils.encode_file_to_base64(Path(load_dir) / x)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\work\gen-pipe\gen-env\Lib\site-packages\gradio_client\utils.py", line 689, in encode_file_to_base64
    with open(f, "rb") as file:
         ^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: 'data:image\\png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg=='
```

**Comment by TriptSharma** [comment]
sample code for reference:
```
    placeholder_img = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQImWNgYGBgAAAABQABh6FO1AAAAABJRU5ErkJggg=="
    resolution: tuple = (896, 1152)
    model: str = "juggernautXL_v8Rundiffusion.safetensors"
    lora_1: str | None = "sd_xl_offset_example-lora_1.0"
    lora_1_weight: int | float = 1
    refiner: None = None
    refiner_weight: float = 0.5
    prompt: str = "astronaut on a horse"

    client = Client("https://a23884f5d2e9044cb9.gradio.live/")

    client.predict(
        False,  
        prompt, 
        "unrealistic, saturated, high contrast, big nose, painting, drawing, sketch, cartoon, anime, manga, render, CG, 3d, watermark, signature, label",
        ["Fooocus V2", "Fooocus Photograph", "Fooocus Negative", "Fooocus Sharp", "Fooocus Masterpiece", "Fooocus Enhance", "Fooocus Cinematic",],
        "Quality",
        f'{resolution[0]}×{resolution[1]} <span style="color: grey;"> | 1:2 </span>',
        1,
        "png",
        "0",
        False,
        6, 3, model, 
        refiner if refiner else "None", 
        refiner_weight if refiner else 0.5,
        True, lora_1 if lora_1 else "None", lora_1_weight,
        True, "None", 1,
        True, "None", 1,
        True, "None", 1,
        True, "None", 1, 
        True, "", 
        "Disabled", placeholder_img, ["Left"],
        placeholder_img,  "", 
        placeholder_img,  
        True,
        True,
        True,
        False,
        1.5,  0.8,  0.3,  
        7,
        2,
        "dpmpp_2m_sde_gpu", 
        "karras",  
        "Default (model)",
        -1, -1, -1, -1, -1, -1, 
        False, False, False, False,
        64, 128,
        "joint", 
        0.25,  
        False,
        1.01, 1.02, 0.99, 0.95, 
        False,
        False,
        "None",
        1,  
        0.618,
        False,
        False,
        0,  
        False,  
        False,  
        "fooocus",
        placeholder_img, 0.5, 0.6, "ImagePrompt",  
        placeholder_img, 0.5, 0.6, "ImagePrompt", 
        placeholder_img, 0.5, 0.6, "ImagePrompt", 
        placeholder_img, 0.5, 0.6, "ImagePrompt", 
        False, 0, 
        False, 
        None,  
        False if upscale_mode == False else True,
        "Disabled",
        "Before First Enhancement",
        "Original Prompts",  
        False, 
        "",  
        "",  
        "",  
        "sam", "full", "vit_b", 0.25, 0.3, 0, False,"v2.6", 1, 0.618, 0, False, False, "",  "",  "",  
        "sam", "full", "vit_b", 0.25, 0.3, 0, False,"v2.6", 1, 0.618, 0, False, False, "",  "",  "",  
        "sam", "full", "vit_b", 0.25, 0.3, 0, False,"v2.6", 1, 0.618, 0, False, 
        fn_index=67
    )
```
